name: Java CI with Maven and Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  publish-docker:
    needs: build  
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and tag Docker image
      run: |
        docker build -t ezwhc/M3S07:latest .
        docker tag ezwhc/M3S07:latest ezwhc/M3S07:$(date +%Y%m%d%H%M%S)

    - name: Push Docker image to Docker Hub
      run: |
        docker push ezwhc/M3S07:latest
        docker push ezwhc/M3S07:$(date +%Y%m%d%H%M%S)
